sudo: required
language: java
services:
  - docker
script:
  - mvn clean package
after_success:
  - docker build -t test/devsecops:1.0 .
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
