sudo: required
language: java
services:
  - docker
before_install:
  - docker build -t test/devsecops:1.0 .
script:
  - mvn clean package
cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'
